spring:
  application:
    name: lazy-deploy
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

lazydeploy:
  base-url: https://api.bflist.io/v2/bf4
  api:
    page-size: 100
  monitoring:
    interval: 30s
  channels:
    email:
      from: ${MAIL_FROM:${MAIL_USERNAME:}}
  servers:
    - id: lost
      enabled: true
      display-name: "! -LOST- CONQUEST CLASSICS | ALL MAPS | 60Hz !"
      identifiers:
        guid: 494eef2a-0155-4df3-91b0-58f565cc5f53
        ip: 131.196.199.123
        port: 25226
      rules: &default-rules
        - type: MAP_IN
          enabled: true
          parameters:
            values: &favorite-maps
              - MP_Prison
              - XP0_Metro
              - XP3_MarketPl
              - XP1_003
              - XP2_004
              - MP_Abandoned
              - MP_Tremors
              - MP_Flooded
        - type: PLAYER_COUNT_AT_LEAST
          enabled: true
          parameters:
            value: 60
      notification-channels: &default-channels
        - type: LOGGING
          enabled: ${LOGGING_NOTIFICATION_ENABLED:true}
        - type: EMAIL
          enabled: true
          parameters:
            to: ${NOTIFICATION_EMAIL:}

    - id: server-2
      enabled: true
      identifiers:
        guid: 9138463d-f3af-47b0-a42e-4d33da4ec9f1
      rules:
        - type: MAP_IN
          enabled: true
          parameters:
            values: *favorite-maps
        - type: PLAYER_COUNT_AT_LEAST
          enabled: true
          parameters:
            value: 50
      notification-channels: *default-channels
#
#    - id: server-3
#      enabled: true
#      identifiers:
#        guid: 58fb3dfa-6e01-40c0-b4e8-d4bdeb07e646
#      rules: &fifty-player-rules
#        - type: MAP_IN
#          enabled: true
#          parameters:
#            values: *favorite-maps
#        - type: PLAYER_COUNT_AT_LEAST
#          enabled: true
#          parameters:
#            value: 50
#      notification-channels: *default-channels
#
#    - id: server-4
#      enabled: true
#      identifiers:
#        guid: 74cd6f06-a696-4157-979c-fb594f00362d
#      rules: *fifty-player-rules
#      notification-channels: *default-channels
#
#    - id: server-5
#      enabled: true
#      identifiers:
#        guid: 98a60c12-be3b-45fa-a8c7-b96fa9efb503
#      rules: *fifty-player-rules
#      notification-channels: *default-channels
#
#    - id: server-6
#      enabled: true
#      identifiers:
#        guid: c4fad2a1-5336-4f1c-9b14-730ff588ff9d
#      rules:
#        - type: MAP_IN
#          enabled: true
#          parameters:
#            values: *favorite-maps
#        - type: PLAYER_COUNT_AT_LEAST
#          enabled: true
#          parameters:
#            value: 40
#      notification-channels: *default-channels
