INSERT INTO battlefield_map (id, display_name, enabled, expansion, metadata, created_at, updated_at)
VALUES
    ('MP_Siege', 'Siege of Shanghai', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Prison', 'Operation Locker', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Flooded', 'Flood Zone', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Naval', 'Paracel Storm', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Journey', 'Golmud Railway', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Damage', 'Dawnbreaker', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Tremors', 'Lancang Dam', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Abandoned', 'Operation Firestorm 2014', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MP_Hainan', 'Hainan Resort', TRUE, 'Base Game', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP0_Metro', 'Operation Metro 2014', TRUE, 'Second Assault', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP0_Caspi', 'Caspian Border 2014', TRUE, 'Second Assault', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP0_Oman', 'Gulf of Oman 2014', TRUE, 'Second Assault', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP0_Firestorm', 'Operation Firestorm 2014', TRUE, 'Second Assault', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP1_001', 'Silk Road', TRUE, 'China Rising', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP1_002', 'Altai Range', TRUE, 'China Rising', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP1_003', 'Guilin Peaks', TRUE, 'China Rising', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP1_004', 'Dragon Pass', TRUE, 'China Rising', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP2_001', 'Lost Islands', TRUE, 'Naval Strike', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP2_002', 'Nansha Strike', TRUE, 'Naval Strike', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP2_003', 'Wave Breaker', TRUE, 'Naval Strike', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP2_004', 'Operation Mortar', TRUE, 'Naval Strike', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP3_001', 'Sunken Dragon', TRUE, 'Dragon''s Teeth', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP3_002', 'Propaganda', TRUE, 'Dragon''s Teeth', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP3_MarketPl', 'Pearl Market', TRUE, 'Dragon''s Teeth', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP3_004', 'Lumphini Garden', TRUE, 'Dragon''s Teeth', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP4_Arctic', 'Operation Whiteout', TRUE, 'Final Stand', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP4_SubBase', 'Hammerhead', TRUE, 'Final Stand', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP4_WlkrFtry', 'Hangar 21', TRUE, 'Final Stand', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP4_WtrTret', 'Giants of Karelia', TRUE, 'Final Stand', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP5_001', 'Operation Outbreak', TRUE, 'Community Operations', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP6_CMP', 'Dragon Valley 2015', TRUE, 'Legacy Operations', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP6_Night', 'Zavod: Graveyard Shift', TRUE, 'Night Operations', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XP7_001', 'Operation Outbreak', TRUE, 'Community Operations', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
